/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WhiteLabellingRouteImport } from './routes/white-labelling'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentCallbackRouteImport } from './routes/payment-callback'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExportRouteImport } from './routes/export'
import { Route as CustomPackagingRouteImport } from './routes/custom-packaging'
import { Route as CorporateSupplyRouteImport } from './routes/corporate-supply'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WholesaleIndexRouteImport } from './routes/wholesale.index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WholesalePortalRouteImport } from './routes/wholesale.portal'
import { Route as WholesaleApplyRouteImport } from './routes/wholesale.apply'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminWholesaleRouteImport } from './routes/admin.wholesale'
import { Route as AdminVariantsRouteImport } from './routes/admin.variants'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRedirectsRouteImport } from './routes/admin.redirects'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPreviewRouteImport } from './routes/admin.preview'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'
import { Route as ApiPublicWebhooksFlutterwaveRouteImport } from './routes/api/public/webhooks/flutterwave'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteLabellingRoute = WhiteLabellingRouteImport.update({
  id: '/white-labelling',
  path: '/white-labelling',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment-callback',
  path: '/payment-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomPackagingRoute = CustomPackagingRouteImport.update({
  id: '/custom-packaging',
  path: '/custom-packaging',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateSupplyRoute = CorporateSupplyRouteImport.update({
  id: '/corporate-supply',
  path: '/corporate-supply',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleIndexRoute = WholesaleIndexRouteImport.update({
  id: '/wholesale/',
  path: '/wholesale/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WholesalePortalRoute = WholesalePortalRouteImport.update({
  id: '/wholesale/portal',
  path: '/wholesale/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleApplyRoute = WholesaleApplyRouteImport.update({
  id: '/wholesale/apply',
  path: '/wholesale/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWholesaleRoute = AdminWholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVariantsRoute = AdminVariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedirectsRoute = AdminRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksFlutterwaveRoute =
  ApiPublicWebhooksFlutterwaveRouteImport.update({
    id: '/api/public/webhooks/flutterwave',
    path: '/api/public/webhooks/flutterwave',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate-supply': typeof CorporateSupplyRoute
  '/custom-packaging': typeof CustomPackagingRoute
  '/export': typeof ExportRoute
  '/faq': typeof FaqRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/white-labelling': typeof WhiteLabellingRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/wholesale/apply': typeof WholesaleApplyRoute
  '/wholesale/portal': typeof WholesalePortalRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/wholesale/': typeof WholesaleIndexRoute
  '/api/public/webhooks/flutterwave': typeof ApiPublicWebhooksFlutterwaveRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate-supply': typeof CorporateSupplyRoute
  '/custom-packaging': typeof CustomPackagingRoute
  '/export': typeof ExportRoute
  '/faq': typeof FaqRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/white-labelling': typeof WhiteLabellingRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/wholesale/apply': typeof WholesaleApplyRoute
  '/wholesale/portal': typeof WholesalePortalRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/wholesale': typeof WholesaleIndexRoute
  '/api/public/webhooks/flutterwave': typeof ApiPublicWebhooksFlutterwaveRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate-supply': typeof CorporateSupplyRoute
  '/custom-packaging': typeof CustomPackagingRoute
  '/export': typeof ExportRoute
  '/faq': typeof FaqRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/white-labelling': typeof WhiteLabellingRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/wholesale/apply': typeof WholesaleApplyRoute
  '/wholesale/portal': typeof WholesalePortalRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/wholesale/': typeof WholesaleIndexRoute
  '/api/public/webhooks/flutterwave': typeof ApiPublicWebhooksFlutterwaveRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/corporate-supply'
    | '/custom-packaging'
    | '/export'
    | '/faq'
    | '/order-confirmed'
    | '/payment-callback'
    | '/privacy'
    | '/terms'
    | '/track-order'
    | '/white-labelling'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/inquiries'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/preview'
    | '/admin/products'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/variants'
    | '/admin/wholesale'
    | '/category/$slug'
    | '/products/$slug'
    | '/recipes/$slug'
    | '/wholesale/apply'
    | '/wholesale/portal'
    | '/admin/'
    | '/products/'
    | '/recipes/'
    | '/wholesale/'
    | '/api/public/webhooks/flutterwave'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/corporate-supply'
    | '/custom-packaging'
    | '/export'
    | '/faq'
    | '/order-confirmed'
    | '/payment-callback'
    | '/privacy'
    | '/terms'
    | '/track-order'
    | '/white-labelling'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/inquiries'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/preview'
    | '/admin/products'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/variants'
    | '/admin/wholesale'
    | '/category/$slug'
    | '/products/$slug'
    | '/recipes/$slug'
    | '/wholesale/apply'
    | '/wholesale/portal'
    | '/admin'
    | '/products'
    | '/recipes'
    | '/wholesale'
    | '/api/public/webhooks/flutterwave'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/corporate-supply'
    | '/custom-packaging'
    | '/export'
    | '/faq'
    | '/order-confirmed'
    | '/payment-callback'
    | '/privacy'
    | '/terms'
    | '/track-order'
    | '/white-labelling'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/inquiries'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/preview'
    | '/admin/products'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/variants'
    | '/admin/wholesale'
    | '/category/$slug'
    | '/products/$slug'
    | '/recipes/$slug'
    | '/wholesale/apply'
    | '/wholesale/portal'
    | '/admin/'
    | '/products/'
    | '/recipes/'
    | '/wholesale/'
    | '/api/public/webhooks/flutterwave'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CorporateSupplyRoute: typeof CorporateSupplyRoute
  CustomPackagingRoute: typeof CustomPackagingRoute
  ExportRoute: typeof ExportRoute
  FaqRoute: typeof FaqRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WhiteLabellingRoute: typeof WhiteLabellingRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  WholesaleApplyRoute: typeof WholesaleApplyRoute
  WholesalePortalRoute: typeof WholesalePortalRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  WholesaleIndexRoute: typeof WholesaleIndexRoute
  ApiPublicWebhooksFlutterwaveRoute: typeof ApiPublicWebhooksFlutterwaveRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/white-labelling': {
      id: '/white-labelling'
      path: '/white-labelling'
      fullPath: '/white-labelling'
      preLoaderRoute: typeof WhiteLabellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-callback': {
      id: '/payment-callback'
      path: '/payment-callback'
      fullPath: '/payment-callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-packaging': {
      id: '/custom-packaging'
      path: '/custom-packaging'
      fullPath: '/custom-packaging'
      preLoaderRoute: typeof CustomPackagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-supply': {
      id: '/corporate-supply'
      path: '/corporate-supply'
      fullPath: '/corporate-supply'
      preLoaderRoute: typeof CorporateSupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/': {
      id: '/wholesale/'
      path: '/wholesale'
      fullPath: '/wholesale/'
      preLoaderRoute: typeof WholesaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wholesale/portal': {
      id: '/wholesale/portal'
      path: '/wholesale/portal'
      fullPath: '/wholesale/portal'
      preLoaderRoute: typeof WholesalePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/apply': {
      id: '/wholesale/apply'
      path: '/wholesale/apply'
      fullPath: '/wholesale/apply'
      preLoaderRoute: typeof WholesaleApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wholesale': {
      id: '/admin/wholesale'
      path: '/wholesale'
      fullPath: '/admin/wholesale'
      preLoaderRoute: typeof AdminWholesaleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/variants': {
      id: '/admin/variants'
      path: '/variants'
      fullPath: '/admin/variants'
      preLoaderRoute: typeof AdminVariantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redirects': {
      id: '/admin/redirects'
      path: '/redirects'
      fullPath: '/admin/redirects'
      preLoaderRoute: typeof AdminRedirectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview': {
      id: '/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/flutterwave': {
      id: '/api/public/webhooks/flutterwave'
      path: '/api/public/webhooks/flutterwave'
      fullPath: '/api/public/webhooks/flutterwave'
      preLoaderRoute: typeof ApiPublicWebhooksFlutterwaveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminPreviewRoute: typeof AdminPreviewRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRedirectsRoute: typeof AdminRedirectsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminVariantsRoute: typeof AdminVariantsRoute
  AdminWholesaleRoute: typeof AdminWholesaleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminPreviewRoute: AdminPreviewRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRedirectsRoute: AdminRedirectsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminVariantsRoute: AdminVariantsRoute,
  AdminWholesaleRoute: AdminWholesaleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CorporateSupplyRoute: CorporateSupplyRoute,
  CustomPackagingRoute: CustomPackagingRoute,
  ExportRoute: ExportRoute,
  FaqRoute: FaqRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  WhiteLabellingRoute: WhiteLabellingRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  WholesaleApplyRoute: WholesaleApplyRoute,
  WholesalePortalRoute: WholesalePortalRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  WholesaleIndexRoute: WholesaleIndexRoute,
  ApiPublicWebhooksFlutterwaveRoute: ApiPublicWebhooksFlutterwaveRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
